### ISSUE TITLE
"The input string '0.4' was not in a correct format" when randomizing

### ISSUE THREAD

**Issue by Erzangel** [Nifyr/A-Little-Secret-Ingredient#1]
Before getting started on this issue, I want to thank you so much for making this randomizer ❤ I am looking forward to trying out the model swaps the most!

## Issue description

When running the randomizer, upon clicking the "Randomize and export" button, the app crashes. In Visual Studio, using the code from 09a4ebfe261e3cf076e46533cf92591ce986f134, I get the following error message:

![image](https://github.com/Nifyr/A-Little-Secret-Ingredient/assets/57399897/7c2bcc0b-faae-4c0c-848d-3714674c74a9)

I have also tried the v1.0.0 release from GitHub, which yields the same error, but somehow with a value of 1.5 (and not 0.4).

- I am using a dump of FE Engage 2.0.0, made using Yuzu. I tried redumping the game thinking I had a bad game dump, but it seems to be fine
- I have .NET SDK 7.0 installed, I have also installed the Runtime version but nothing changed
- I have tried this with settings selected, with nothing selected, and the result is still the same
- I am on Windows 10, with French locale. Which I'm thinking is maybe the issue, but I am not sure.

Will provide more screenshots of the stack trace below. I do not know if this issue is specific to my system, I will try to run the randomizer on my macOS laptop this Thursday.

## Screenshot of stack trace

![image](https://github.com/Nifyr/A-Little-Secret-Ingredient/assets/57399897/0d86fe43-2006-4a08-be1d-c97836a6974d)

**Comment by Nifyr** [comment]
lmao, i probably made the same mistake the pokémon bdsp devs made. [https://youtu.be/fB2C8q42X64?t=596](https://youtu.be/fB2C8q42X64?t=596)
Committed a fix for it just now. If you want to, you can grab the latest commit and confirm if that fixed the issue.

**Comment by Erzangel** [comment]
Awesome! I'll let you know as soon as I try it out & confirm whether or not the issue is fixed 👍

**Comment by Erzangel** [comment]
The randomizer now works! Yipee! 🎉

Thank you so much for fixing it so quickly! I'm going to have fun with this for a while now, up until new features make it even more fun to retry! 

A little bonus: the randomized assets I got are hilarious for the game's intro

![image](https://github.com/Nifyr/A-Little-Secret-Ingredient/assets/57399897/5a45257e-7fde-4fc7-b195-3f8e40f53b6d)

**Comment by Nifyr** [comment]
love to see it lol
