### ISSUE TITLE
Crash on attempting to view Celica's inheritable skills

### ISSUE THREAD

**Issue by Kinetic1000** [Nifyr/A-Little-Secret-Ingredient#3]
Celica doesn't appear in the list of emblems to inherit skills from in the Ring Chamber. If I select a unit with Celica equipped, the game crashes. Additionally, on the two bond levels I got with her, it didn't show any skills. (This can probably occur with any emblem.)

Output folder:
[Output.zip](https://github.com/Nifyr/A-Little-Secret-Ingredient/files/12043713/Output.zip)

Save file:
[Manual7.zip](https://github.com/Nifyr/A-Little-Secret-Ingredient/files/12043716/Manual7.zip)

**Comment by Nifyr** [comment]
Hmm... It appears that shuffling bond level tables left celica with emblem alear's bond level table. The game must not have liked this...

**Comment by Nifyr** [comment]
Just ended up removing the bond level table shuffle feature for v1.3.0 as other randomizer options made it obsolete anyways.
