### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by SylphOswell** [Nifyr/A-Little-Secret-Ingredient#4]
Hello,

even after using multiple different randomnizer settings I always get this error message:
[ErrorRandomnizer.txt](https://github.com/Nifyr/A-Little-Secret-Ingredient/files/13404938/ErrorRandomnizer.txt)
 
Even if I don´t change anything I always get this error message.

I even tried out multiple versions of .netFrameWork but it doesn´t solve this issue. Even older versions of this randomnizer doesnt work for me.

Does the randomnizer need something specifically from the engage rom? I dumped it myself from the newest switch version 17.0. 

Thanks in advance.

**Comment by Nifyr** [comment]
It appears your dump somehow contains unexpected data... Are you sure you're loading an **unmodified** dump of Fire Emblem Engage **2.0.0**?

**Comment by SylphOswell** [comment]
Yes, i dumped it from my switch, had to merge the files and then extracted the contents with a computer program.

**Comment by SylphOswell** [comment]
Nvm, I know where the problems is.

Thank you anyway. 👍
