### ISSUE TITLE
"Match Proficiency" doesn't seem to work.

### ISSUE THREAD

**Issue by battlecarrier** [Nifyr/A-Little-Secret-Ingredient#5]
I'm not sure if this is just user error, but I can't seem to get randomized classes to match a character's proficiencies.
I've tried every sort of class distribution, both with and without randomizing proficiencies. I still seem to see classes distributed to characters with zero matching proficiencies no matter how I set it up.

Version 1.4.2

**Comment by Nifyr** [comment]
Nice catch! I looked into it, and the setting to match proficiencies was accidentally hooked up to the wrong checkbox (the "grouped shuffle" checkbox). Fixed in next release.
